version: '3.8'
services:
  db:
    image: postgres:15.2
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: